import type { FastifyInstance } from "fastify";
import { authRoutes } from "./auth.js";
import { tenantRoutes } from "./tenants.js";
import { centerRoutes } from "./centers.js";
import { productRoutes } from "./products.js";
import { formRoutes } from "./forms.js";
import { customerRoutes } from "./customers.js";
import { appointmentRoutes } from "./appointments.js";
import { visitRoutes } from "./visits.js";
import { magicLinkRoutes } from "./magic-link.js";
import { revisionRoutes } from "./revisions.js";
import { workflowRoutes } from "./workflow.js";
import { messageTemplateRoutes } from "./message-templates.js";
import { segmentRoutes } from "./segments.js";
import { campaignRoutes } from "./campaigns.js";
import { dashboardRoutes } from "./dashboard.js";
import { analyticsRoutes } from "./analytics.js";
import { userRoutes } from "./users.js";
import { doctorRoutes } from "./doctors.js";
import { publicApiRoutes } from "./public.js";

export async function registerRoutes(server: FastifyInstance) {
  server.get("/health", async () => ({ status: "ok" }));
  const prefix = "/api/v1";
  await server.register(authRoutes, { prefix });
  await server.register(tenantRoutes, { prefix });
  await server.register(centerRoutes, { prefix });
  await server.register(productRoutes, { prefix });
  await server.register(formRoutes, { prefix });
  await server.register(customerRoutes, { prefix });
  await server.register(appointmentRoutes, { prefix });
  await server.register(visitRoutes, { prefix });
  await server.register(magicLinkRoutes, { prefix });
  await server.register(revisionRoutes, { prefix });
  await server.register(workflowRoutes, { prefix });
  await server.register(messageTemplateRoutes, { prefix });
  await server.register(segmentRoutes, { prefix });
  await server.register(campaignRoutes, { prefix });
  await server.register(dashboardRoutes, { prefix });
  await server.register(analyticsRoutes, { prefix });
  await server.register(userRoutes, { prefix });
  await server.register(doctorRoutes, { prefix });
  await server.register(publicApiRoutes, { prefix });
}
